import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  FolderSync, Search, ArrowUpRight, FileText, 
  Clock, Sparkles, AlertCircle, ArrowLeft, X, Copy, Check
} from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { getApiUrl } from '../services/api';
import { cn } from '../lib/utils';

interface ProjectStory {
  id: number;
  prompt: string;
  generatedText: string;
  createdAt: string;
}

export function ProjectHubWorkspace() {
  const navigate = useNavigate();
  const [projects, setProjects] = useState<ProjectStory[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [selectedProject, setSelectedProject] = useState<ProjectStory | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [copied, setCopied] = useState(false);

  const fetchHistory = async () => {
    setLoading(true);
    setError('');
    try {
      const response = await axios.get(`${getApiUrl()}/history`);
      if (response.data.success) {
        setProjects(response.data.data || []);
      } else {
        setError('Failed to fetch history logs.');
      }
    } catch (err: any) {
      console.error(err);
      setError('Failed to fetch projects history. Ensure the backend server is running.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchHistory();
  }, []);

  const formatDate = (dateString: string) => {
    const options: Intl.DateTimeFormatOptions = { 
      year: 'numeric', 
      month: 'short', 
      day: 'numeric', 
      hour: '2-digit', 
      minute: '2-digit' 
    };
    return new Date(dateString).toLocaleDateString(undefined, options);
  };

  const copyTextToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 3000);
  };

  const filteredProjects = projects.filter(p => 
    p.prompt.toLowerCase().includes(searchTerm.toLowerCase()) || 
    p.generatedText.toLowerCase().includes(searchTerm.toLowerCase())
  );

  return (
    <div className="p-8 max-w-7xl mx-auto min-h-screen font-sans text-white bg-[#060608]">
      
      {/* Header */}
      <header className="mb-10 flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate('/')}
            className="p-2.5 bg-white/5 hover:bg-white/10 text-brand-light-grey hover:text-white rounded-xl transition-all"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div className="h-8 w-px bg-white/10" />
          <div>
            <div className="flex items-center gap-2 text-brand-blue mb-1">
              <FolderSync className="w-5 h-5 text-brand-blue" />
              <span className="text-xs font-bold uppercase tracking-widest font-mono">Archive Hub</span>
            </div>
            <h1 className="text-3xl font-extrabold tracking-tight">Project Hub</h1>
            <p className="text-brand-light-grey text-xs mt-1">
              View your creative history logs and past screenplays generated by the Bubble Tree database.
            </p>
          </div>
        </div>

        <button 
          onClick={() => navigate('/module/script-making')}
          className="bg-brand-blue hover:bg-blue-600 text-white px-5 py-2.5 rounded-xl text-xs font-bold shadow-lg shadow-brand-blue/20 flex items-center gap-2 transition-all hover:-translate-y-0.5 active:scale-95"
        >
          <Sparkles className="w-4 h-4" />
          Create New Screenplay
        </button>
      </header>

      {/* Toolbar / Search */}
      <div className="flex flex-col md:flex-row gap-4 mb-8 bg-brand-grey/10 p-4 rounded-2xl border border-white/5">
        <div className="flex-1 relative">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-brand-light-grey" />
          <input 
            type="text" 
            placeholder="Search prompt query or generated content..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-brand-dark border border-white/10 rounded-xl pl-10 pr-4 py-2 text-xs text-white placeholder-brand-light-grey/50 focus:border-brand-blue/50 focus:outline-none transition-colors"
          />
        </div>
        <button 
          onClick={fetchHistory}
          className="bg-white/5 hover:bg-white/10 text-white border border-white/10 rounded-xl px-4 py-2 text-xs font-bold uppercase tracking-wider transition-colors shrink-0"
        >
          Refresh Archive
        </button>
      </div>

      {/* Layout Split: Lists on Left, Slide-over detail panel on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Project Grid / List View */}
        <div className={cn(
          "transition-all duration-300",
          selectedProject ? "lg:col-span-6" : "lg:col-span-12"
        )}>
          {loading ? (
            <div className="p-16 text-center text-brand-light-grey/60 font-mono text-xs animate-pulse">Loading database archive logs...</div>
          ) : error ? (
            <div className="bg-red-500/10 border border-red-500/20 p-6 rounded-2xl flex items-start gap-3 text-red-400 text-xs">
              <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
              <div>
                <h4 className="font-bold mb-1">Retrieval Failure</h4>
                <p>{error}</p>
              </div>
            </div>
          ) : filteredProjects.length === 0 ? (
            <div className="text-center p-16 rounded-[28px] bg-white/[0.02] border border-dashed border-white/10">
              <FileText className="w-12 h-12 mx-auto text-brand-light-grey/30 mb-4" />
              <h3 className="text-white font-semibold text-lg">No screenplays found</h3>
              <p className="text-brand-light-grey text-xs mt-1">Go to the screenplay workspace to write or generate AI co-writer drafts.</p>
            </div>
          ) : (
            <div className={cn(
              "grid gap-6",
              selectedProject ? "grid-cols-1" : "grid-cols-1 md:grid-cols-2 lg:grid-cols-3"
            )}>
              {filteredProjects.map((proj, idx) => (
                <motion.div 
                  key={proj.id}
                  initial={{ opacity: 0, y: 15 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: idx * 0.05 }}
                  onClick={() => setSelectedProject(proj)}
                  className={cn(
                    "cursor-pointer p-6 rounded-[24px] border transition-all duration-300 flex flex-col justify-between min-h-[200px] hover:-translate-y-0.5",
                    selectedProject?.id === proj.id 
                      ? "border-brand-blue bg-white/10 shadow-[0_8px_30px_rgb(0,0,0,0.12)]" 
                      : "border-white/5 bg-brand-grey/20 hover:bg-white/[0.04]"
                  )}
                >
                  <div className="space-y-4">
                    <div className="flex justify-between items-center text-[10px] font-mono font-bold tracking-wider text-brand-light-grey/50">
                      <span className="text-brand-blue">#SC-0{proj.id}</span>
                      <div className="flex items-center gap-1.5">
                        <Clock className="w-3.5 h-3.5" />
                        <span>{formatDate(proj.createdAt)}</span>
                      </div>
                    </div>
                    <div className="space-y-1">
                      <h4 className="font-extrabold text-sm text-white line-clamp-2 leading-snug group-hover:text-brand-blue transition-colors">
                        {proj.prompt}
                      </h4>
                      <p className="text-brand-light-grey text-[11px] leading-relaxed line-clamp-3">
                        {proj.generatedText}
                      </p>
                    </div>
                  </div>

                  <div className="pt-4 border-t border-white/5 flex items-center justify-between text-xs text-brand-light-grey/85">
                    <span className="text-[10px] font-bold font-mono bg-white/5 px-2.5 py-1 rounded-lg">Draft</span>
                    <button 
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedProject(proj);
                      }}
                      className="flex items-center gap-1 font-bold text-brand-blue hover:text-blue-400 transition-colors"
                    >
                      <span>Read Text</span>
                      <ArrowUpRight className="w-3.5 h-3.5" />
                    </button>
                  </div>
                </motion.div>
              ))}
            </div>
          )}
        </div>

        {/* Detailed Side Panel View */}
        <AnimatePresence>
          {selectedProject && (
            <motion.div 
              initial={{ opacity: 0, x: 50 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 50 }}
              className="lg:col-span-6 bg-[#141416] border border-white/[0.05] rounded-[28px] p-6 lg:p-8 shadow-2xl relative space-y-6 animate-fadeIn"
            >
              <div className="flex justify-between items-start border-b border-white/5 pb-4">
                <div className="space-y-1 pr-8">
                  <span className="text-[10px] font-mono font-bold text-brand-blue uppercase tracking-widest">Original Prompt</span>
                  <h3 className="text-white text-base font-bold leading-relaxed">{selectedProject.prompt}</h3>
                  <p className="text-[10px] text-brand-light-grey/40 font-mono">Date Logged: {formatDate(selectedProject.createdAt)}</p>
                </div>
                <button 
                  onClick={() => setSelectedProject(null)}
                  className="p-2 bg-white/5 hover:bg-white/10 text-white rounded-full transition-colors shrink-0"
                  title="Close Detail Panel"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="flex justify-between items-center text-xs">
                <span className="text-[10px] font-bold font-mono bg-white/5 px-2.5 py-1 rounded-lg text-brand-light-grey/65">Screenplay Markdown text</span>
                <button
                  onClick={() => copyTextToClipboard(selectedProject.generatedText)}
                  className="px-3 py-1.5 bg-white/5 hover:bg-white/10 text-white rounded-lg text-[10px] font-bold uppercase tracking-wider transition-colors flex items-center gap-1.5 border border-white/5"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-green-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy screenplay'}</span>
                </button>
              </div>
              
              <div className="p-6 bg-brand-dark/60 border border-white/5 rounded-2xl text-[#E8E8E8] whitespace-pre-wrap leading-relaxed max-h-[500px] overflow-y-auto font-mono text-xs custom-scrollbar-light select-text">
                {selectedProject.generatedText}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

      </div>

      <style dangerouslySetInnerHTML={{ __html: `
        .custom-scrollbar-light::-webkit-scrollbar { width: 6px; }
        .custom-scrollbar-light::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar-light::-webkit-scrollbar-thumb { background: rgba(255, 255, 255, 0.05); border-radius: 10px; }
      `}} />
    </div>
  );
}
